name: vector_basics
author: Ewetumo Alexander <trinoxf@gmail.com>
description: provides a set of basic examples to get you started with sparkflow
dependencies:
  sparkflow: any
  hub: any
  fxpub: any
  spark_utils: any
dependency_overrides:
  sparkflow:
    path: ../sparkflow
  hub:
    path: ../hub
  fxpub:
    path: ../fxpub
  spark_utils:
    path: ../spark_utils

